services:
  tanstack-start-template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanstack-start-template
    restart: unless-stopped
    ports:
      - 4000:3000
    env_file:
      - .env.production
    environment:
      VITE_BASE_URL: http://localhost:3000
      VITE_APP_TITLE: ${VITE_APP_TITLE}
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
