name: tanstack-start-template
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tanstack-start-template
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
