name: tanstack-start-template
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tanstack-start-template

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'dracula'
